seed = "stage3-hardened"
profile = "default/linux/amd64/23.0/no-multilib/hardened"
bases = ["tini", "ca-certificates"]

clean_seed = true
packages = ["net-dns/dnscrypt-proxy"]

[tar_filter_options]
vardbpkg = true
locales = true
